### ISSUE TITLE
Semantics and Naming convention

### ISSUE THREAD

**Issue by tijaniabdellatif** [FSFULLSTACK/TEAM2#2]
The problem in your last commit with this is id [90188aa]  (https://github.com/FSFULLSTACK/TEAM2/commit/90188aad29d566883661edf40f3a07ea743ffd0e) is semantics and naming classes convention in html5 and CSS3 

### Semantics  :
In HTML Semantics it's important to respect the priority of the semantics tags, for example : 
- `nav` should always be inside `header`
- `section` should always be inside `main`

### Naming classes : 

- In css files i can see that you use names of to call them directly to put in css like this :

`nav img{
    width:6rem;
    margin-left: 3rem;
}`

It's a bad practice to call the name in css due to the repetition of balise names in the HTML5 docs for this you can use classes like references (documentation above)

- Using variables in css make things easier and also rise the code performance, the key word `var()` can call the value of the proprety memorized in a variable name

## Reading documentations : 

- [HTML SEMANTICS](https://www.semrush.com/blog/semantic-html5-guide/)
- [Naming classes convention](http://getbem.com/naming/)

## Steps to Reproduce

- [ ] Refactor the code by respecting the semantics
- [ ] use classes name instead of tag names
- [ ] use the keyword `var` to call your variables

**Have fun building** 👍 💯

**Comment by nrhjj** [comment]
Understood coach. I've tried to reproduce my code while respecting your instructions. the final version is pushed in main branch.
Thank you .

**Comment by pharaonIT** [comment]
Check the commit with that id : [ee05aeb](https://github.com/FSFULLSTACK/TEAM2/commit/ee05aeb0f8fe4ce78583c61747614d5493f5db56)

**Comment by pharaonIT** [comment]
Done
